// get all subscribers
GET http://localhost:3000/subscribers


###
// get one subscribers
GET  http://localhost:3000/subscribers/66faf5065ec678d79e1512c3


### 
// create new subscribers
POST   http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "new User 3",
    "subscribedToChannel": "Already subscribed"
}


###
// delete one subscriber
DELETE http://localhost:3000/subscribers/66fb0383b420c10bc1ca64ac


###
// udpate a subscriber

PATCH  http://localhost:3000/subscribers/66faff32bc4f019d0ce35d45
Content-Type: application/json

{
    "name": "update to new user 3",
    "subscribedToChannel": "user 3 subscription updated "
}
