// get all subscribers
GET http://localhost:3000/subscribers


###
// get one subscribers
GET  http://localhost:3000/subscribers/66faf5065ec678d79e1512c3


### 
// create new subscribers
POST   http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "new User 3",
    "subscribedToChannel": "Already subscribed"
}


###
// delete one subscriber
DELETE http://localhost:3000/subscribers/66faf5065ec678d79e1512c3


###
// udpate a subscriber

PATCH  http://localhost:3000/subscribers/66faf4c465e2b679f5c51e9d
Content-Type: application/json

{
    "name": "update to new user 2",
    "subscribedToChannel": "subscription updated"
}
